services:
  postgres:
    image: postgres:15
    volumes:
      - ./rating.backup:/backup/rating.backup
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
